[package]
name = "tg_voice_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
teloxide = "0.9.1"
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"
dotenvy = "0.15"
log = "0.4"
pretty_env_logger = "0.4"